### ISSUE TITLE
Review zadání

### ISSUE THREAD

**Issue by janavitvar** [filipkralson/2122ALG2-Kral-Autobazar#1]
Zajímavý nápad, ale zkúste to víc přizpůsobit realitě. Modelujte jen to, co potřebujete pro funkcionalitu aplikace. Jaký je vztah mezi zaměstnanci a prodejci. Zrušte omezující počty - pracujeme už s dynamickými poli. Zadání je ta první část. Jaké budou metody v jednotlivých třídách, bude vidět z class diagramu. Raději napište, jak bude vypadat menu z pohledu uživatele (funkční specifikace). Popište, jaká data budou v souborech.

**Comment by filipkralson** [comment]
Omezující počet jsem zavedl hlavně kvůli souboru s auty, bude jich tam asi tak 30-40. U zaměstnanců ho klidně odstraním.
